import {useEffect,useState} from 'react';import {Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {router} from 'expo-router';import {api} from '../src/api/mobilePos';const C={bg:'#f6f2e9',card:'#fffcf6',ink:'#24231e',muted:'#68665f',line:'#ded7cb',accent:'#ad3b19'};
export default function Deposit(){const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[opening,setOpening]=useState(''),[counts,setCounts]=useState({drawer_cash:'',shift_gcash:'',lockbox_total:'',total_gcash:'',notes:''});
async function load(){setBusy(true);try{const r=await api('/deposit-controls');const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j)}catch(e:any){Alert.alert('Deposit Control',e.message||'Unable to load')}finally{setBusy(false)}}
async function post(path:string,body:any={}){setBusy(true);try{const r=await api(path,{method:'POST',body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Request failed');await load()}catch(e:any){Alert.alert('Deposit Control',e.message)}finally{setBusy(false)}}
useEffect(()=>{load()},[]);const a=data?.active;
return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.page}><Head title="Deposit Control" onBack={()=>router.replace('/')} onRefresh={load}/><Text style={s.title}>Start. Count. <Text style={s.em}>Close.</Text></Text><Text style={s.copy}>Live shift reconciliation. Financial counts require a connection so server balances remain authoritative.</Text>
{!a?<View style={s.card}><Text style={s.h}>Start shift</Text><Field label="Opening cash" value={opening} set={setOpening}/><Btn label={busy?'WORKING...':'START SHIFT'} disabled={busy||!opening} onPress={()=>post('/deposit-controls',{opening_cash:Number(opening)})}/></View>:
<View style={s.card}><Text style={s.h}>Shift #{a.id}</Text><Text style={s.copy}>Opened by {a.user?.name||'cashier'} · {new Date(a.opened_at).toLocaleString()}</Text>{!a.closed_at?<Btn label="CAPTURE CLOSING BALANCES" disabled={busy} onPress={()=>post('/deposit-controls/'+a.id+'/close')}/>:
<><Text style={s.section}>FINAL COUNTS</Text><Field label="Drawer cash" value={counts.drawer_cash} set={v=>setCounts({...counts,drawer_cash:v})}/><Field label="Shift GCash" value={counts.shift_gcash} set={v=>setCounts({...counts,shift_gcash:v})}/><Field label="Lockbox total" value={counts.lockbox_total} set={v=>setCounts({...counts,lockbox_total:v})}/><Field label="Total GCash" value={counts.total_gcash} set={v=>setCounts({...counts,total_gcash:v})}/><TextInput style={s.input} placeholder="Notes (optional)" value={counts.notes} onChangeText={v=>setCounts({...counts,notes:v})}/><Btn label="SUBMIT RECONCILIATION" disabled={busy} onPress={()=>post('/deposit-controls/'+a.id+'/reconcile',{...counts,drawer_cash:Number(counts.drawer_cash),shift_gcash:Number(counts.shift_gcash),lockbox_total:Number(counts.lockbox_total),total_gcash:Number(counts.total_gcash)})}/></>}</View>}
<View style={s.card}><Text style={s.h}>Previous snapshots</Text>{(data?.history?.data??[]).slice(0,8).map((x:any)=><View style={s.row} key={x.id}><View><Text style={s.bold}>Shift #{x.id} · {x.user?.name}</Text><Text style={s.small}>{new Date(x.opened_at).toLocaleString()}</Text></View><Text style={s.bold}>{x.reconciliation?Number(x.reconciliation.shift_variance).toFixed(2):'—'}</Text></View>)}</View></ScrollView></SafeAreaView>}
function Head({title,onBack,onRefresh}:any){return <View style={s.head}><Pressable onPress={onBack}><Text style={s.link}>← DASHBOARD</Text></Pressable><Text style={s.eye}>LOAD CAFE / {title.toUpperCase()}</Text><Pressable onPress={onRefresh}><Text style={s.link}>REFRESH</Text></Pressable></View>}function Field({label,value,set}:any){return <View><Text style={s.label}>{label}</Text><TextInput keyboardType="decimal-pad" style={s.input} value={value} onChangeText={set} placeholder="0.00"/></View>}function Btn(p:any){return <Pressable style={[s.btn,p.disabled&&{opacity:.5}]} disabled={p.disabled} onPress={p.onPress}><Text style={s.btnText}>{p.label}</Text></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.bg},page:{padding:18,paddingBottom:40},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eye:{fontSize:8,fontWeight:'900',letterSpacing:1,color:C.accent},link:{fontSize:9,fontWeight:'900',color:C.accent},title:{fontSize:32,fontWeight:'900',color:C.ink,marginTop:22},em:{fontFamily:'serif',fontWeight:'400',color:C.accent},copy:{fontSize:11,lineHeight:18,color:C.muted,marginTop:8},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:6,padding:16,marginTop:16},h:{fontSize:18,fontWeight:'900',color:C.ink},section:{fontSize:9,fontWeight:'900',letterSpacing:1,color:C.accent,marginTop:16},label:{fontSize:10,fontWeight:'700',color:C.muted,marginTop:12,marginBottom:5},input:{borderWidth:1,borderColor:C.line,borderRadius:4,padding:12,backgroundColor:'#fff',color:C.ink,marginTop:8},btn:{backgroundColor:C.ink,padding:14,borderRadius:4,alignItems:'center',marginTop:14},btnText:{color:'#fff',fontSize:10,fontWeight:'900'},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12,borderTopWidth:1,borderColor:'#ece5da'},bold:{fontSize:11,fontWeight:'800',color:C.ink},small:{fontSize:9,color:C.muted,marginTop:3}});