import {database} from '../db/database';import {connectBluetoothPrinter,disconnectBluetoothPrinter,getPairedPrinters,isBluetoothPrinterConnected,printReceipt,requestBluetoothPermissions,type ReceiptBlock} from '@honeypathkar/react-native-thermal-printer';
const LOCAL_PRINTER_KEY='android_printer_override';
export type PrintSettings={print_enabled?:boolean;print_auto_print?:boolean;print_paper_width?:number;print_store_name?:string;print_store_address?:string;print_store_phone?:string;print_footer?:string;print_channel?:string;print_bluetooth_name?:string;print_bluetooth_address?:string;updated_at?:string};
export async function getPrintSettings():Promise<PrintSettings|null>{const db=await database(),r=await db.getFirstAsync<{value:string}>("SELECT value FROM app_meta WHERE key='print_settings'");return r?.value?JSON.parse(r.value):null}
export async function getLocalPrinter(){const db=await database(),r=await db.getFirstAsync<{value:string}>("SELECT value FROM app_meta WHERE key=?",[LOCAL_PRINTER_KEY]);return r?.value?JSON.parse(r.value):null}
export async function selectLocalPrinter(device:{name?:string;address:string}){const db=await database();await db.runAsync("INSERT OR REPLACE INTO app_meta(key,value) VALUES(?,?)",LOCAL_PRINTER_KEY,JSON.stringify({name:device.name||'Bluetooth printer',address:device.address}));return device}
export async function clearLocalPrinter(){const db=await database();await db.runAsync("DELETE FROM app_meta WHERE key=?",[LOCAL_PRINTER_KEY])}
export async function pairedPrinters(){await requestBluetoothPermissions();return getPairedPrinters()}
export async function connectConfiguredPrinter(){const s=await getPrintSettings(),local=await getLocalPrinter(),address=local?.address||s?.print_bluetooth_address;if(!address)throw new Error('No printer selected. Pair the printer in Android Bluetooth settings, then select it here.');try{await requestBluetoothPermissions()}catch{throw new Error('Bluetooth permission was denied. Allow Nearby devices / Bluetooth permission for Bypass Grill POS.')}try{if(await isBluetoothPrinterConnected())await disconnectBluetoothPrinter();await connectBluetoothPrinter(address)}catch(e:any){throw new Error('Unable to connect to '+(local?.name||s?.print_bluetooth_name||address)+'. Make sure the printer is powered on and paired with this phone. '+(e?.message||''))}return{...(s||{}),print_bluetooth_name:local?.name||s?.print_bluetooth_name,print_bluetooth_address:address}}
export async function disconnectPrinter(){await disconnectBluetoothPrinter()}
const money=(n:number)=>'P'+Number(n||0).toFixed(2);
export function receiptBlocks(data:any,s:PrintSettings):ReceiptBlock[]{const b:any[]=[{type:'text',value:(s.print_store_name||'BYPASS GRILL').toUpperCase(),align:'center',bold:true,size:'large'}];if(s.print_store_address)b.push({type:'text',value:s.print_store_address,align:'center'});if(s.print_store_phone)b.push({type:'text',value:'Tel: '+s.print_store_phone,align:'center'});b.push({type:'divider',char:'='},{type:'text',value:data.order?.number?'Receipt # : '+data.order.number:'Receipt',bold:true},{type:'text',value:'Date      : '+(data.order?.date||new Date().toLocaleString())});if(data.order?.cashier)b.push({type:'text',value:'Cashier   : '+data.order.cashier});if(data.order?.type)b.push({type:'text',value:'Order     : '+data.order.type});if(data.order?.customer)b.push({type:'text',value:'Customer  : '+data.order.customer});b.push({type:'divider'});for(const i of data.items??[])b.push({type:'item',name:i.name,quantity:Number(i.qty),price:Number(i.price),amount:Number(i.total)});b.push({type:'divider'});if(data.totals?.subtotal!=null)b.push({type:'row',left:'Subtotal',right:money(data.totals.subtotal)});if(Number(data.totals?.discount)>0)b.push({type:'row',left:'Discount',right:'-'+money(data.totals.discount)});b.push({type:'row',left:'TOTAL',right:money(data.totals?.total),bold:true,size:'large'},{type:'divider',char:'='});if(data.payment){b.push({type:'row',left:'Payment',right:data.payment.method||''},{type:'row',left:'Paid',right:money(data.payment.amount)});if(Number(data.payment.change)>0)b.push({type:'row',left:'Change',right:money(data.payment.change)});b.push({type:'divider',char:'='})}b.push({type:'text',value:s.print_footer||'Thank you for dining with us!',align:'center'},{type:'feed',lines:3},{type:'cut'});return b}
export async function printBypassReceipt(data:any,force=false){const s=await getPrintSettings();if(!s?.print_enabled)return{success:false,skipped:true,error:'Printing is disabled in web settings'};if(!force&&!s.print_auto_print)return{success:false,skipped:true,error:'Auto print is disabled'};await connectConfiguredPrinter();const paper=s.print_paper_width===48?'80mm':'58mm';return printReceipt(receiptBlocks(data,s),'bluetooth',{paperWidth:paper,copies:1})}
export async function testPrint(){const s=await connectConfiguredPrinter();return printReceipt(receiptBlocks({order:{number:'TEST',date:new Date().toLocaleString(),type:'Test'},items:[{name:'Test Item',qty:1,price:1,total:1}],totals:{subtotal:1,discount:0,total:1}},s),'bluetooth',{paperWidth:s.print_paper_width===48?'80mm':'58mm',copies:1})}
